# NumPy Library Notes

In [1]:
import numpy as np

In [2]:
# Creating an 1D array with numpy

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
# Accessing elements
print(arr[0])
print(arr[1])
print(arr[2])

1
2
3


In [4]:
# Creating an 2D array with numpy

arr = np.array(([1, 2, 3], [4, 5, 6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# Accessing elements in a 2D array
print(arr[0,1]) # -------------> 0th row 1st column
print(arr[1,2]) # -------------> 1st row 2nd column
print(arr[0,0]) # -------------> 0th row 0th column

2
6
1


In [6]:
# Finding the dimension of the array using ndim

arr1 = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
print(arr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(arr1.ndim)

2


In [8]:
# Finding the number of rows and columns using shape
# arr1 has 3 rows and 3 columns
print(arr1.shape)

(3, 3)


In [9]:
# arange() fucntion

arr2 = np.arange(1, 10)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# creating a 0s matrix

arr0 = np.zeros((3,3))
print(arr0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# creating a 1s matrix

array_1 = np.ones((3,3))
print(array_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# Creating an Identity matrix

id_mat = np.eye(3)
print(id_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# ARRAY MANIPULATION


In [13]:
# Reshape the array

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:")
print(array1)
l = array1.reshape(3,3) 
print("After reshaping:")
print(l)

Original array:
[1 2 3 4 5 6 7 8 9]
After reshaping:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# flatten function

print(l)
l = l.flatten(order="F")
print(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7 2 5 8 3 6 9]


In [15]:
# Transpose function

l = l.reshape(3,3)
print(l)
t = np.transpose(l)
print(t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# ARITHMATIC OPERATIONS WITH ARRAY

In [16]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
b = np.array([10, 10, 10])
b

array([10, 10, 10])

In [18]:
# Addition
print("Matrix Addition")
print(np.add(a, b))
print('\n')
# Subraction
print("Matrix Subraction")
print(np.subtract(a, b))
print('\n')
# Multiply
print("Matrix Mutiplication")
print(np.multiply(a, b))
print('\n')
# Divide
print("Matrix Mutiplication")
print(np.divide(a, b))
print('\n')


Matrix Addition
[[10 11 12]
 [13 14 15]
 [16 17 18]]


Matrix Subraction
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]


Matrix Mutiplication
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


Matrix Mutiplication
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]




In [20]:
# Slicing Array

a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
a[:5]

array([0, 1, 2, 3, 4])

In [24]:
s = slice(2, 12, 2)
a[s]

array([ 2,  4,  6,  8, 10])

# ITERATING THROUGH ARRAY 

In [25]:
a = np.arange(0, 45, 5)
a = a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [26]:
# Using nditer 
for x in np.nditer(a):
    print(x, end=' ')

0 5 10 15 20 25 30 35 40 

In [28]:
# Order of Iteration 


print("Order C")
for x in np.nditer(a, order='C'):    # Using nditer in Column order
    print(x, end=' ')


print("\nOrder F")
for x in np.nditer(a, order='F'):    # Using nditer in Row order
    print(x, end=' ')

Order C
0 5 10 15 20 25 30 35 40 
Order F
0 15 30 5 20 35 10 25 40 